In [12]:
from c4 import Board
from c4 import Player
from c4 import Game
import tensorflow as tf

p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)

print("TensorFlow version:", tf.__version__)

2023-08-10 16:08:03.677159: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 16:08:03.738565: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 16:08:03.739269: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-10 16:08:04.823983: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


TensorFlow version: 2.12.0


In [16]:
# mnist = tf.keras.datasets.mnist

# (x_train, y_train), (x_test, y_test) = mnist.load_data()
# x_train, x_test = x_train / 255.0, x_test / 255.0

TypeError: unsupported operand type(s) for /: 'list' and 'float'

In [11]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(1, 42)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1)
])

NameError: name 'tf' is not defined

In [3]:
predictions = model(x_train[:1]).numpy()
predictions

NameError: name 'x_train' is not defined

In [19]:
tf.nn.softmax(predictions).numpy()

NameError: name 'predictions' is not defined

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.7266874

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

2023-08-04 09:30:49.797105: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2935 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1415 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1074 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0887 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0725 - accuracy: 0.9772


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0739 - accuracy: 0.9768 - 393ms/epoch - 1ms/step


[0.07394569367170334, 0.9768000245094299]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4055951e-09, 3.1053040e-09, 1.2045449e-05, 6.5231441e-05,
        1.6034424e-12, 2.5815334e-08, 7.0989249e-13, 9.9992037e-01,
        1.2248761e-07, 2.2203312e-06],
       [8.1749449e-06, 2.5656732e-07, 9.9996841e-01, 6.0214948e-06,
        5.5506777e-14, 6.1036517e-06, 5.5484197e-06, 8.4413717e-12,
        5.3944832e-06, 2.1765012e-11],
       [6.6370540e-06, 9.9465239e-01, 5.9056521e-04, 4.5372904e-05,
        3.6116864e-05, 5.9579620e-06, 1.7020860e-05, 4.3878858e-03,
        2.5076745e-04, 7.2934936e-06],
       [9.9982578e-01, 3.1586209e-09, 4.2579279e-05, 1.4920378e-06,
        1.4079143e-07, 1.7211894e-06, 3.4295437e-05, 5.3113003e-05,
        8.3019614e-07, 4.0023264e-05],
       [2.1268941e-05, 6.4739378e-09, 6.8995573e-06, 8.2539486e-08,
        9.9146771e-01, 8.6461250e-07, 1.1956776e-05, 2.2060904e-05,
        1.6368120e-05, 8.4526446e-03]], dtype=float32)>

In [9]:
print(len(x_train), len(y_train))


60000 60000


In [1]:
from c4 import Board
from c4 import Player
from c4 import Game
import json

p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)


game_results = game.generate_training_data(1)

# print(game_results[0])

# for game, result in zip(x_train, y_train):
#     print(result)
#     print(game)

# with open('game_data.csv', 'w') as f:
#     for  in x_train:
#         f.write(json.dumps(x.tolist()) + "\n")
#     for y in y_train:
#         f.write(str(y) + "\n"

In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

2023-08-10 21:41:38.373167: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 21:41:38.960714: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 21:41:38.962859: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-10 21:41:47.950321: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [6]:
from c4 import Board
from c4 import Player
from c4 import Game
import json

p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)


game_results = game.generate_training_data(2)

# print(game_results[0])

# for game, result in zip(x_train, y_train):
#     print(result)
#     print(game)


with open('game_data.csv', 'w') as f:
    for result in game_results:
        f.write(json.dumps(result.tolist()) + "\n")

# def build_model(states, actions):
#     model = Sequential()
#     model.add(Flatten(input_shape=(1, 42)))
#     model.add(Dense(24, activation='relu'))
#     model.add(Dense(24, activation='relu'))
#     model.add(Dense(1, activation='linear'))
#     return model

# x_train, y_train = [], []

# for result in game_results:
#     x_train.append(result[:-1])
#     y_train.append(result[-1])

In [4]:
model = build_model(x_train, y_train)
model.predict([[[1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 1]]])

1/1 [==============================] - 0s 244ms/step


array([[2.1835377]], dtype=float32)

1000 1000


In [1]:
from c4 import Board
from c4 import Player
from c4 import Game
import json
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)


game_results = game.generate_training_data(5)

with open('game_data.csv', 'a') as f:
    for result in game_results:
        f.write(json.dumps(result.tolist()) + "\n")

def build_model(states, actions):
    model = Sequential()
    model.add(Flatten(input_shape=(1, 42)))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(1, activation='linear'))
    return model

x_train, y_train = [], []

for result in game_results:
    x_train.append(result[:-1])
    y_train.append(result[-1])
        
model = build_model(x_train, y_train)
model.predict([[[1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2
                 ['}|']

2023-08-11 12:10:04.011362: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 12:10:04.073334: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 12:10:04.074238: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-11 12:10:05.160429: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


AttributeError: 'list' object has no attribute 'tolist'

In [12]:
import training
import json
import numpy as np

results = []

with open('game_data.csv', 'r') as f:
    data = f.readlines()
    
for line in data:
    results.append(json.loads(line))
    
def expand_game_board_state(flat):
    game, victor = np.array(flat[:-1]), flat[-1]
    
    game = np.reshape(game, (6,7))
    

    return game, victor

expand_game_board_state(results[2])

[[ 0  0  1  0  0  0  0]
 [ 1  0 -1  1  0  0  0]
 [-1  1 -1 -1  0  0 -1]
 [-1 -1  1  1 -1 -1  1]
 [-1  1  1 -1  1 -1  1]
 [ 1  1  1 -1 -1 -1  1]]
-1
