In [2]:
from c4 import Board
from c4 import Player
from c4 import Game
import tensorflow as tf

p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [14]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.15122661,  0.11362897, -0.07275763,  0.78981906, -0.7079394 ,
        -0.435087  , -0.29896978, -0.2611984 , -0.26959276,  0.05738875]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.11761086, 0.11327107, 0.09400963, 0.22273304, 0.04980999,
        0.06543569, 0.07497727, 0.07786343, 0.07721256, 0.1070765 ]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.7266874

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

2023-08-04 09:30:49.797105: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2935 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1415 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1074 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0887 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0725 - accuracy: 0.9772


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0739 - accuracy: 0.9768 - 393ms/epoch - 1ms/step


[0.07394569367170334, 0.9768000245094299]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4055951e-09, 3.1053040e-09, 1.2045449e-05, 6.5231441e-05,
        1.6034424e-12, 2.5815334e-08, 7.0989249e-13, 9.9992037e-01,
        1.2248761e-07, 2.2203312e-06],
       [8.1749449e-06, 2.5656732e-07, 9.9996841e-01, 6.0214948e-06,
        5.5506777e-14, 6.1036517e-06, 5.5484197e-06, 8.4413717e-12,
        5.3944832e-06, 2.1765012e-11],
       [6.6370540e-06, 9.9465239e-01, 5.9056521e-04, 4.5372904e-05,
        3.6116864e-05, 5.9579620e-06, 1.7020860e-05, 4.3878858e-03,
        2.5076745e-04, 7.2934936e-06],
       [9.9982578e-01, 3.1586209e-09, 4.2579279e-05, 1.4920378e-06,
        1.4079143e-07, 1.7211894e-06, 3.4295437e-05, 5.3113003e-05,
        8.3019614e-07, 4.0023264e-05],
       [2.1268941e-05, 6.4739378e-09, 6.8995573e-06, 8.2539486e-08,
        9.9146771e-01, 8.6461250e-07, 1.1956776e-05, 2.2060904e-05,
        1.6368120e-05, 8.4526446e-03]], dtype=float32)>

In [26]:
print(len(x_train), len(y_train))

for x in x_train[:10]:
    print(x)

60000 60000
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.   

In [2]:
from c4 import Board
from c4 import Player
from c4 import Game


p1 = Player("AI")
p2 = Player("AI")
game = Game(p1, p2)

x_train = []
y_train = []

game.play_games(10, True)
    

Player: 1 wins!
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [2, 2, 0, 1, 0, 0, 0],
       [1, 1, 1, 2, 0, 0, 0],
       [1, 1, 1, 2, 0, 0, 2],
       [1, 1, 2, 1, 2, 2, 2]])
Player: 2 wins!
array([[0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 2, 0, 0, 0],
       [2, 2, 2, 1, 0, 0, 0],
       [2, 2, 2, 1, 0, 0, 0],
       [2, 1, 1, 2, 1, 0, 0],
       [1, 1, 1, 2, 1, 0, 0]])
Player: 2 wins!
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 2, 0],
       [0, 2, 2, 2, 2, 1, 0],
       [0, 2, 1, 2, 1, 1, 0],
       [2, 2, 1, 2, 1, 1, 1]])
Game is a draw :-/
array([[1, 2, 2, 1, 1, 2, 2],
       [2, 1, 2, 2, 1, 1, 1],
       [2, 1, 1, 1, 2, 2, 1],
       [1, 1, 2, 2, 1, 1, 2],
       [1, 2, 2, 2, 1, 2, 2],
       [1, 1, 1, 2, 1, 2, 2]])
Player: 1 wins!
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0],
       [2, 2, 1, 1, 1, 1, 0]])
Player: 2 wi